# Use an official OpenJDK runtime as the base image
FROM eclipse-temurin:17-jdk-jammy

# Copy the built JAR file to the container
COPY target/*.jar app.jar

# Command to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
